In [1]:
!pip install numpy

In [1]:
import numpy as np

np.__version__

'1.26.4'

In [2]:
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [3]:
arr = np.array(list1)
type(arr)

numpy.ndarray

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
arr[0]

1

In [6]:
arr[-1]

5

In [7]:
arr[2] = 100

In [8]:
arr

array([  1,   2, 100,   4,   5])

In [9]:
arr[5] = 10

IndexError: index 5 is out of bounds for axis 0 with size 5

In [10]:
len(arr)

5

In [11]:
arr.size

5

In [12]:
arr.shape

(5,)

In [22]:
list2 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
arr2 = np.array(list2)
type(arr2)

numpy.ndarray

In [15]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
len(arr2) # Number of rows

3

arr[0] # first row \
arr[1] # second row \
arr[2] # third row

In [17]:
len(arr2[0]) # Number of column in first row

4

In [18]:
arr2.size # Total number of elements

12

In [19]:
arr2.shape

(3, 4)

In [20]:
len(arr2.shape) # find number of dimensions

2

In [23]:
arr = np.arange(10) # from 0 to stop-1
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr = np.arange(0,10) # from start to stop-1
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr = np.arange(0,10,2) # from start to stop-1 with step as increment
arr

array([0, 2, 4, 6, 8])

In [29]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [30]:
arr.dtype

dtype('float64')

In [31]:
arr = np.zeros(5, dtype=np.int32)
arr

array([0, 0, 0, 0, 0], dtype=int32)

In [33]:
arr.dtype

dtype('int32')

In [35]:
arr2 = np.zeros((4,5))
arr2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
arr2 = np.zeros([4,5])
arr2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
np.ones(4)

array([1., 1., 1., 1.])

In [42]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [43]:
np.linspace(0,10,4) # create evenly spaced elements over the given interval

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [44]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [45]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [47]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
arr.T # transpose

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [53]:
list2 = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = np.array(list2)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [55]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
np.dot(arr2, np.eye(3,3))

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

#### Random values

In [61]:
np.random.seed(42)
np.random.rand(3) # uniform distribution over [0,1]

array([0.37454012, 0.95071431, 0.73199394])

In [62]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

In [63]:
np.random.rand(4,5)  # uniform distribution over [0,1]

array([[0.59865848, 0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985, 0.83244264],
       [0.21233911, 0.18182497, 0.18340451, 0.30424224, 0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465]])

In [64]:
np.random.randn(4)  # standard normal distribution

array([-0.7033438 , -2.13962066, -0.62947496,  0.59772047])

In [65]:
np.random.randn(4,5) 

array([[ 2.55948803,  0.39423302,  0.12221917, -0.51543566, -0.60025385],
       [ 0.94743982,  0.291034  , -0.63555974, -1.02155219, -0.16175539],
       [-0.5336488 , -0.00552786, -0.22945045,  0.38934891, -1.26511911],
       [ 1.09199226,  2.77831304,  1.19363972,  0.21863832,  0.88176104]])

#### Random integer(s)
Random integer between a range low (inclusive) and high (exclusive)

In [67]:
np.random.randint(1,100) # Single value generated

78

In [72]:
arr = np.random.randint(1,100,10) # 3rd argument is number of values to be generated
arr

array([23, 62, 88, 37, 99, 44, 86, 91, 35, 65])

In [73]:
arr.min()

23

In [76]:
arr.argmin()

0

In [77]:
arr.min()

99

In [78]:
arr.argmax()

4

In [79]:
arr.mean()

63.0

In [80]:
arr1 = np.arange(25)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

#### Convert single dimension array to 2-D

In [86]:
arr2 = arr1.reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [83]:
arr2 = arr1.reshape(1,25)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [84]:
arr2.shape

(1, 25)

In [92]:
arr1.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [87]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### Convert 2-D array to 1-D

In [88]:
arr2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [89]:
arr2.reshape(25,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [90]:
arr2.reshape(arr2.size,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [91]:
matrix = np.array([[1,2],[3,4]])
matrix

array([[1, 2],
       [3, 4]])

#### Single array operations

In [93]:
np.sqrt(matrix)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [94]:
np.square(matrix)

array([[ 1,  4],
       [ 9, 16]])

In [95]:
np.sum(matrix)

10

In [96]:
np.max(matrix)

4

In [97]:
np.min(matrix)

1

#### Multiple array operations

In [101]:
arr1 = np.array([6, 2, -1])
arr2 = np.array([5, -8, 2])

print(arr1)
print(arr2)
print('Add:', np.add(arr1, arr2))
print('Subtract:', np.subtract(arr1, arr2))
print('Multiply:', np.multiply(arr1, arr2))
print('Divide:', np.divide(arr1, arr2))
print('Dot product:', np.dot(arr1, arr2))

[ 6  2 -1]
[ 5 -8  2]
Add: [11 -6  1]
Subtract: [ 1 10 -3]
Multiply: [ 30 -16  -2]
Divide: [ 1.2  -0.25 -0.5 ]
Dot product: 12


In [103]:
list2 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
arr2 = np.array(list2)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [104]:
arr2[1][2]

7

In [105]:
arr2[1,2]

7

In [106]:
arr2[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [109]:
arr2[0:2, 2:]

array([[3, 4],
       [7, 8]])

In [114]:
arr2[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [116]:
arr2[0:len(arr2), 0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [119]:
arr1 = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = [[7,8,9],[4,5,6],[1,2,3]]

print(arr1)
print(arr2)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[7, 8, 9], [4, 5, 6], [1, 2, 3]]


In [129]:
print(np.add(arr1, arr2))

[[ 8 10 12]
 [ 8 10 12]
 [ 8 10 12]]


In [126]:
print(np.subtract(arr1, arr2))

[[-6 -6 -6]
 [ 0  0  0]
 [ 6  6  6]]


In [125]:
print(np.multiply(arr1, arr2))

[[ 7 16 27]
 [16 25 36]
 [ 7 16 27]]


In [127]:
print(np.divide(arr1, arr2))

[[0.14285714 0.25       0.33333333]
 [1.         1.         1.        ]
 [7.         4.         3.        ]]


In [128]:
print(np.dot(arr1, arr2))

[[ 18  24  30]
 [ 54  69  84]
 [ 90 114 138]]


In [131]:
arr = np.zeros((10,10))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [132]:
arr.shape

(10, 10)

In [135]:
for i in range(arr.shape[1]):
    arr[i] = i
arr    

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

#### extract even numbered rows

In [136]:
arr[[0,2,4,6,8]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [140]:
arr[[i for i in range(len(arr)) if i % 2 == 0]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [141]:
[i for i in range(len(arr)) if i % 2 == 0]

[0, 2, 4, 6, 8]

In [142]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

#### extract all even numbers into a single dimension array

In [143]:
arr[arr % 2 == 0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])